# The Configuration

# Set the default version number
version-template: '0.0.1'

# Update the version number in the project configuration file
version-files:
  - file: package.json
    version-template: '$MAJOR.$MINOR.$PATCH'

artifacts:
  - name: latest-build
    files: extension-latest.zip

name-template: 'v$NEXT_PATCH_VERSION 🎉'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
