# The Configuration
name: Release Drafter

artifacts:
  - name: latest-build
    files: extension-latest.zip

name-template: 'v$NEXT_PATCH_VERSION 🎉'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: [Here](https://github.com/StrongTheDev/avr-utils/compare/v$PREVIOUS_TAG...v$RESOLVED_VERSION)
