name: Extension Builder Action

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      
      - name: Setup Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check and setup caches
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules

      - name: Install dependencies
        run: npm install
      
      - name: Run build script
        run: npm run build
        # run: npm run avr-utils
      
      # - name: Rename application entry file
      #   run: sed -i "s#src/extension.js#out/main.js#" package.json
      
      - name: Package Extension
        run: npx vsce pack
      
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-latest-${{ github.sha }}
          path: "*.vsix"